# Generated by Django 4.1.2 on 2022-11-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ESite_App", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingaddress",
            name="address",
            field=models.CharField(default=False, max_length=400),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="city",
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="fname",
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="lname",
            field=models.CharField(default=False, max_length=20),
        ),
    ]
