# Generated by Django 4.1.2 on 2022-11-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ESite_App", "0003_alter_shippingaddress_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingaddress",
            name="address",
            field=models.CharField(default=None, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="city",
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="fname",
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="lname",
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
