# Generated by Django 4.1.2 on 2022-12-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ESite_App", "0006_backgroundimage"),
    ]

    operations = [
        migrations.RemoveField(model_name="item", name="categories",),
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("Camping Tent", "Camping Tent"),
                    ("Survival Gadget", "Survival Gadget"),
                    ("Clothing", "Clothing"),
                    ("Cooking", "Cooking"),
                ],
                default=None,
                max_length=20,
            ),
        ),
    ]
