# Generated by Django 4.1.2 on 2022-12-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ESite_App", "0008_remove_shippingaddress_fname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="Color",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="item",
            name="Color2",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="item",
            name="Color3",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="item",
            name="Color4",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="item",
            name="Color5",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="item",
            name="Color6",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
