# Generated by Django 4.1.2 on 2022-12-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ESite_App", "0009_item_color_item_color2_item_color3_item_color4_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="color",
            field=models.CharField(default="", max_length=20),
        ),
    ]
