# Generated by Django 4.1.2 on 2022-12-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ESite_App", "0011_billingaddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingaddress",
            name="phone_number",
            field=models.IntegerField(default=False),
        ),
    ]
