# Generated by Django 4.1.2 on 2022-12-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ESite_App", "0012_billingaddress_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingaddress",
            name="first_name",
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name="billingaddress",
            name="last_name",
            field=models.CharField(default=None, max_length=40),
        ),
    ]
