# Generated by Django 4.1.2 on 2022-12-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ESite_App", "0013_billingaddress_first_name_billingaddress_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingaddress",
            name="company",
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="first_name",
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="last_name",
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="phone_number",
            field=models.IntegerField(default=False),
        ),
    ]
