# Generated by Django 4.1.2 on 2023-01-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ESite_App",
            "0014_shippingaddress_company_shippingaddress_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="Image_1",
            field=models.ImageField(default=None, upload_to="static/images"),
        ),
        migrations.AddField(
            model_name="item",
            name="Image_2",
            field=models.ImageField(default=None, upload_to="static/images"),
        ),
        migrations.AddField(
            model_name="item",
            name="Image_3",
            field=models.ImageField(default=None, upload_to="static/images"),
        ),
        migrations.AlterField(
            model_name="item",
            name="Images",
            field=models.ImageField(default=None, upload_to="static/images"),
        ),
    ]
