# Generated by Django 4.1.2 on 2023-01-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ESite_App", "0015_item_image_1_item_image_2_item_image_3_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Logo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Logo", models.ImageField(upload_to="")),
            ],
        ),
        migrations.AlterField(
            model_name="item",
            name="Image_1",
            field=models.ImageField(
                blank=True, default=None, upload_to="static/images"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="Image_2",
            field=models.ImageField(
                blank=True, default=None, upload_to="static/images"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="Image_3",
            field=models.ImageField(
                blank=True, default=None, upload_to="static/images"
            ),
        ),
    ]
